package(default_visibility = ["//visibility:public"])

config_setting(
    name = "windows",
    constraint_values = ["@platforms//os:windows"],
)

alias(
    name = "dm",
    actual = "//src:dm",
)

alias(
    name = "dm_run",
    actual = "//src/tools:dm_run",
)

alias(
    name = "tokenizer_miner",
    actual = "//src/tokenizer:tokenizer_miner",
)

filegroup(
    name = "all_binaries",
    srcs = [
        "//src:dm",
        "//src/tokenizer:hust_tokenize",
        "//src/tokenizer:tokenizer_miner",
        "//src/tools:chuo_miner",
        "//src/tools:dm_bpe",
        "//src/tools:dm_bpe_gpu",
        "//src/tools:dm_bpe_dropout",
        "//src/tools:dm_connect",
        "//src/tools:dm_fast_wordpiece",
        "//src/tools:dm_gpe",
        "//src/tools:dm_gpe_gpu",
        "//src/tools:dm_parity_bpe",
        "//src/tools:dm_run",
        "//src/tools:dm_sentencepiece",
        "//src/tools:dm_sentencepiece_gpu",
        "//src/tools:dm_tokenizer_lab",
        "//src/tools:dm_tokenizer_lab_gpu",
        "//src/tools:dm_unigram",
        "//src/tools:dm_unigram_gpu",
        "//src/tools:dm_volt",
        "//src/tools:dm_volt_gpu",
        "//src/tools:htk_miner",
        "//src/tools:hupp_miner",
        "//src/tools:itemset_mining_bench",
        "//src/tools:kclotree_miner",
        "//src/tools:mfhoi_miner",
        "//src/tools:mhoui_miner",
        "//src/tools:pso_classifier",
        "//src/tools:tipn_houi_miner",
        "//src/tools:tku_miner",
        "//src/tools:tku_pso_miner",
        "//src/tools:tmku_miner",
        "//src/tools:topkphm_miner",
        "//src/tools:vifp_miner",
    ],
)
