package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_sources",
    srcs = glob(["**/*"]),
)

cc_library(
    name = "vulkan_headers",
    hdrs = glob([
        "Vulkan-Headers/include/**/*.h",
        "Vulkan-Headers/include/**/*.hpp",
        "Vulkan-Headers/include/**/*.inc",
    ]),
    includes = ["Vulkan-Headers/include"],
)

cc_library(
    name = "vulkan_hpp_headers",
    hdrs = glob([
        "vulkan/**/*.h",
        "vulkan/**/*.hpp",
    ]),
    includes = ["."],
    deps = [":vulkan_headers"],
)

cc_library(
    name = "glm_headers",
    hdrs = glob([
        "glm/glm/**/*.h",
        "glm/glm/**/*.hpp",
        "glm/glm/**/*.inl",
    ]),
    includes = ["glm"],
)

filegroup(
    name = "glslang_sources",
    srcs = glob([
        "glslang/**/*.c",
        "glslang/**/*.cc",
        "glslang/**/*.cpp",
        "glslang/**/*.h",
        "glslang/**/*.hpp",
    ]),
)

filegroup(
    name = "samples",
    srcs = glob([
        "samples/**/*",
        "RAII_Samples/**/*",
    ]),
)
