#ifndef DM_TINYSTORIES_H
#define DM_TINYSTORIES_H

/*
 * TinyStories pipeline support.
 *
 * Paper: Eldan and Li, "TinyStories: How Small Can Language Models Be
 * and Still Speak Coherent English?", arXiv:2305.07759v2.
 *
 * This module implements the deterministic parts described by the paper:
 *   - sample one verb, one noun, and one adjective from child-vocabulary banks
 *   - sample story feature constraints
 *   - emit the TinyStories short-story generation prompt
 *   - build TinyStories-Instruct style instruction records
 *   - build GPT-Eval grading prompts
 *
 * The paper's actual story text is generated by GPT-3.5/GPT-4 and the
 * grading is performed by GPT-4. Those external model calls are intentionally
 * represented as prompt files instead of fabricated local generations.
 */

int dm_tinystories_cli(int argc, char **argv);

#endif /* DM_TINYSTORIES_H */
